// novo/src/lib/Contact.svelte
<script lang="ts">
  import type { Social } from "../types/shared_data";
  import type { SectionName } from "../types/specified_data";

  export let name: SectionName;
  export let social: Social[];
</script>

<section id="contact">
  <div class="col-md-12">
    <h1 class="section-title">
      <span>
        {#if name}
          {name}
        {:else}
          ???
        {/if}
      </span>
    </h1>
  </div>
  <div class="social-links fa-3x">
    {#if social}
      {#each social as item}
        <span class="m-4">
          <a href={item.url} class="fa-2x">
            <i class={item.class} />
          </a>
        </span>
      {/each}
    {/if}
  </div>
</section>

// velho/src/components/Contact.jsx
import React from "react"

function Contact({ resumeBasicInfo, sharedData }){

    const renderSocialMedias = item => (
        <span key={item.name} className="m-4">
            <a href={item.url} className="fa-2x" target="_blank" rel="noopener noreferrer">
                <i className={`${item.class}`}></i>
            </a>
        </span>
    )

    return (
        <section id="contact">
            <div className="col-md-12">
                <h1 className="section-title" style={{ color: "white" }}>
                    <span>
                        {resumeBasicInfo ? resumeBasicInfo.section_name.contact : "???"}
                    </span>
                </h1>
            </div>
            <div className="social-links fa-3x">
                {
                !!sharedData && sharedData.social.map(renderSocialMedias)
                }
            </div>
        </section>
    )
}

export default Contact
