// novo/src/lib/Skills.svelte
<script lang="ts">
  import type { SkillIcon } from "../types/shared_data";
  import type { SectionName } from "../types/specified_data";

  export let skills: SkillIcon[];
  export let section_name: SectionName;
</script>

<section id="skills">
  <div class="col-md-12">
    <div class="col-md-12">
      <h1 class="section-title">
        <span class="text-white">
          {section_name.skills}
        </span>
      </h1>
    </div>
    <div class="col-md-12 text-center">
      <ul class="list-inline mx-auto skill-icon">
        {#each skills as skill}
          <li class="list-inline-item mx-3">
            <span>
              <div class="text-center skills-tile">
                <i class={skill.class}>
                  <p class="text-center">
                    {skill.name}
                  </p>
                </i>
              </div>
            </span>
          </li>
        {/each}
      </ul>
    </div>
  </div>
</section>

<style>
  div i {
    font-size: "220%";
  }

  div i p.text-center {
    font-size: "30%";
    margin-top: 4px;
  }
</style>

// src/components/Skills.jsx
import React, { useEffect, useState } from "react";

function Skills({ sharedSkills, resumeBasicInfo }){
  const [sectionName, setSectionName] = useState("")
  const [skills, setSkills] = useState([])

  useEffect(() => {
    if (!!resumeBasicInfo) setSectionName(resumeBasicInfo.section_name.skills)
    
    if (!!sharedSkills) setSkills(sharedSkills.icons)
  }, [sharedSkills, resumeBasicInfo])


  const Skill = (skill, i) => (
    <li className="list-inline-item mx-3" key={i}>
      <span>
        <div className="text-center skills-tile">
          <i className={skill.class} style={{ fontSize: "220%" }}>
            <p
              className="text-center"
              style={{ fontSize: "30%", marginTop: "4px" }}
            >
              {skill.name}
            </p>
          </i>
        </div>
      </span>
    </li>
  )


  return (
    <section id="skills">
      <div className="col-md-12">
        <div className="col-md-12">
          <h1 className="section-title">
            <span className="text-white">
              {
                sectionName
              }
            </span>
          </h1>
        </div>
        <div className="col-md-12 text-center">
          <ul className="list-inline mx-auto skill-icon">
            {
              skills.map(Skill)
            }
          </ul>
        </div>
      </div>
    </section>
  )
}

export default Skills;
